#! /usr/bin/ruby
require 'YAML'

# usage: ./ghetto-build profile=whatever --minify 

profile_matcher = /^profile=(.*)$/
profile_path = "util/profiles/"

# defaults
profile = "enchilada"
minify = false

$*.each do |arg|
  minify = true if arg == "--minify"
  profile = arg.match(profile_matcher)[1] if arg.match(profile_matcher)
end

hash = YAML.load_file "#{ profile_path }#{ profile }.js"

# clear previous file
`echo > #{ hash["out"] }`

hash["include"].each do |include|
  # a bit of overhead since not all files end in a newline
  `(cat #{ hash["baseUrl"] }#{ include }.js ; echo) >> #{ hash["out"] }`
end

if minify
  `java -jar util/compiler.jar --js=#{ hash["out"] } \
  --js_output_file=#{ hash["out"] }.min`
end
