var xui;
(function(){xui=function(a){a=a||document;return this.find(a)};idExpr=/^#([\w-]+)$/;xui.extend=function(a){var b=this.prototype;for(var c in a||{})b[c]=a[c];return b};xui.prototype={elements:[],find:function(a){var b=[],c=a.length,d,e,g,f;if(typeof a=="string"&&idExpr.test(a)){this.elements.push(document.getelementsById(a));return this}for(g=0;g<c;g++)if(typeof a[g]=="string"){d=document.querySelectorAll(a[g]);e=d.length;for(f=0;f<e;f++)b.push(d[f])}else if(a[g]instanceof Array)for(var h=0;h<a[g].length;h++){d=
document.querySelectorAll(a[g][h]);e=d.length;for(f=0;f<e;f++)b.push(d[f])}else b.push(a[g]);this.elements=this.elements.concat(this.reduce(b));return this},reduce:function(a,b){var c=[],d,e=a.length;for(d=0;d<e;d++)c.indexOf(a[d],0,b)<0&&c.push(a[d]);return c},removex:function(a,b,c){c=a.slice((c||b)+1||a.length);a.length=b<0?a.length+b:b;return a.push.apply(a,c)},has:function(a){var b=[];this.each(function(c){x$(a).each(function(d){d==c&&b.push(c)})});this.elements=b;return this},not:function(a){for(var b=
this.elements,c=0;c<b.length;c++)x$(a).each(function(d){if(b[c]==d)this.elements=this.removex(b,b.indexOf(b[c]))});return this},add:function(a){this.find([a]);this.elements=this.reduce(this.elements);return this},first:function(){return this.get(0)},get:function(a){return this.elements[a]},eq:function(a,b){b=b?b+1:a+1;this.elements=this.elements.slice(a,b);return this},size:function(){return this.elements.length},each:function(a){for(var b=0,c=this.elements.length;b<c;++b)if(a.call(this,this.elements[b])===
false)break;return this}};var m=[];m.push({inner:function(a){return this.html("inner",a)},outer:function(a){return this.html("outer",a)},top:function(a){return this.html("top",a)},bottom:function(a){return this.html("bottom",a)},remove:function(){return this.html("remove")},before:function(a){return this.html("before",a)},after:function(a){return this.html("after",a)},html:function(a,b){var c=function(e){if(e.firstChild===null)switch(e.tagName){case "UL":return"LI";case "DL":return"DT";case "TR":return"TD";
default:return e.tagName}return e.firstChild.tagName},d=function(e,g){var f={},h=/^<([A-Z][A-Z0-9]*)([^>]*)>(.*)<\/\1>/i;if(h.test(e)){result=h.exec(e);g=result[1];if(result[2]!==""){e=result[2].split(/([A-Z]*\s*=\s*['|"][A-Z0-9:;#\s]*['|"])/i);for(h=0;h<e.length;h++){var i=e[h].replace(/^\s*|\s*$/g,"");if(i!==""&&i!==" "){i=i.split("=");f[i[0]]=i[1].replace(/(["']?)/g,"")}}}e=result[3]}g=document.createElement(g);for(var k in f){h=document.createAttribute(k);h.nodeValue=f[k];g.setAttributeNode(h)}g.innerHTML=
e;return g};this.clean();if(arguments.length==0)return this.elements[0].innerHTML;if(arguments.length==1&&arguments[0]!="remove"){b=a;a="inner"}this.each(function(e){switch(a){case "inner":if(typeof b=="string"){e.innerHTML=b;e=e.getElementsByTagName("SCRIPT");for(var g=e.length,f=0;f<g;f++)eval(e[f].text)}else{e.innerHTML="";e.appendChild(b)}break;case "outer":if(typeof b=="string")b=d(b,c(e));e.parentNode.replaceChild(b,e);break;case "top":if(typeof b=="string")b=d(b,c(e));e.insertBefore(b,e.firstChild);
break;case "bottom":if(typeof b=="string")b=d(b,c(e));e.insertBefore(b,null);break;case "remove":g=e.parentNode;g.removeChild(e);break;case "before":g=e.parentNode;if(typeof b=="string")b=d(b,c(g));g.insertBefore(b,e);break;case "after":g=e.parentNode;if(typeof b=="string")b=d(b,c(g));g.insertBefore(b,e.nextSibling);break}});return this},clean:function(){var a=/\S/;this.each(function(b){for(var c=b.firstChild,d=-1;c;){var e=c.nextSibling;if(c.nodeType==3&&!a.test(c.nodeValue))b.removeChild(c);else c.nodeIndex=
++d;c=e}});return this},attr:function(a,b){if(arguments.length==2){this.each(function(d){d.setAttribute(a,b)});return this}else{var c=[];this.each(function(d){d.getAttribute(a)!=null&&c.push(d.getAttribute(a))});return c}}});m.push({click:function(a){return this.on("click",a)},load:function(a){return this.on("load",a)},submit:function(a){return this.on("submit",a)},touchstart:function(a){return this.on("touchstart",a)},touchmove:function(a){return this.on("touchmove",a)},touchend:function(a){return this.on("touchend",
a)},touchcancel:function(a){return this.on("touchcancel",a)},gesturestart:function(a){return this.on("gesturestart",a)},gesturechange:function(a){return this.on("gesturechange",a)},gestureend:function(a){return this.on("gestureend",a)},orientationchange:function(a){return this.on("orientationchange",a)},on:function(a,b){var c=function(d){window.addEventListener&&d.addEventListener(a,b,false)};this.each(function(d){c(d)});return this}});m.push({setStyle:function(a,b){this.each(function(c){c.style[a]=
b});return this},getStyle:function(a,b){var c=function(d,e){return document.defaultView.getComputedStyle(d,"").getPropertyValue(e)};if(b===undefined)return c(this.first(),a);this.each(function(d){b(c(d,a))});return this},addClass:function(a){var b=this,c=function(d,e){return b.getClassRegEx(e).test(d.className)};this.each(function(d){if(c(d,a)===false)d.className+=" "+a});return this},hasClass:function(a,b){var c=this;if(b===undefined&&this.elements.length==1)return this.getClassRegEx(a).test(c.first().className);
this.each(function(d){c.getClassRegEx(a).test(d.className)==true&&b(d)});return this},removeClass:function(a){if(a===undefined)this.each(function(c){c.className=""});else{var b=this.getClassRegEx(a);this.each(function(c){c.className=c.className.replace(b," ")})}return this},css:function(a){var b=this;this.each(function(){for(var c in a)b.setStyle(c,a[c])});return this||b},reClassNameCache:{},getClassRegEx:function(a){var b=this.reClassNameCache[a];if(!b){b=new RegExp("(?:^|\\s+)"+a+"(?:\\s+|$)");
this.reClassNameCache[a]=b}return b}});m.push({tween:function(a,b){this.each(function(c){emile(c,a,b)});return this}});m.push({xhr:function(a,b,c){if(!/^inner|outer|top|bottom|before|after$/.test(a)){c=b;b=a;a="inner"}var d=c;if(typeof c=="function"){d={};d.callback=c}c||(d={});if(this.first().tagName=="FORM"){d.callback=b;b=this.first().action;d.data=this._toQueryString(this.first());d.method=this.first().method}var e=this;c=new XMLHttpRequest;var g=d.method||"get",f=d.async||false,h=d.data||null;
c.queryString=h;if(d.headers)for(var i=0;i<d.headers.length;i++)c.setRequestHeader(d.headers[i].name,d.headers[i].value);c.open(g,b,f);c.setRequestHeader("X-Requested-With","XMLHttpRequest");c.onload=d.callback!=null?d.callback:function(){e.html(a,this.responseText)};c.send(h);return this}});for(var o=0,r=m.length;o<r;o++)xui.extend(m[o]);window.x$=function(){return new xui(arguments)}})();
(function(m,o){function r(f,h,i){return(f+(h-f)*i).toFixed(3)}function a(f,h,i){return f.substr(h,i||1)}function b(f,h,i){for(var k=2,j,l,n=[],p=[];j=3,l=arguments[k-1],k--;)if(a(l,0)=="r")for(l=l.match(/\d+/g);j--;)n.push(~~l[j]);else{if(l.length==4)l="#"+a(l,1)+a(l,1)+a(l,2)+a(l,2)+a(l,3)+a(l,3);for(;j--;)n.push(parseInt(a(l,1+j*2,2),16))}for(;j--;){k=~~(n[j+3]+(n[j]-n[j+3])*i);p.push(k<0?0:k>255?255:k)}return"rgb("+p.join(",")+")"}function c(f){var h=parseFloat(f);f=f.replace(/^[\-\d\.]+/,"");
return isNaN(h)?{v:f,f:b,u:""}:{v:h,f:r,u:f}}function d(f){var h={},i=g.length,k;e.innerHTML='<div style="'+f+'"></div>';for(f=e.childNodes[0].style;i--;)if(k=f[g[i]])h[g[i]]=c(k);return h}var e=document.createElement("div"),g="backgroundColor borderBottomColor borderBottomWidth borderLeftColor borderLeftWidth borderRightColor borderRightWidth borderSpacing borderTopColor borderTopWidth bottom color fontSize fontWeight height left letterSpacing lineHeight marginBottom marginLeft marginRight marginTop maxHeight maxWidth minHeight minWidth opacity outlineColor outlineOffset outlineWidth paddingBottom paddingLeft paddingRight paddingTop right textIndent top width wordSpacing zIndex".split(" ");
o[m]=function(f,h,i){f=typeof f=="string"?document.getElementById(f):f;i=i||{};var k=d(h);h=f.currentStyle?f.currentStyle:getComputedStyle(f,null);var j,l={},n=+new Date,p=i.duration||200,s=n+p,t,u=i.easing||function(q){return-Math.cos(q*Math.PI)/2+0.5};for(j in k)l[j]=c(h[j]);t=setInterval(function(){var q=+new Date,v=q>s?1:(q-n)/p;for(j in k)f.style[j]=k[j].f(l[j].v,k[j].v,u(v))+k[j].u;if(q>s){clearInterval(t);i.after&&i.after()}},10)}})("emile",this);
